name = App-ModuleAudit

[ReadmeFromPod]
filename = docs/README.rakudoc

[PruneFiles]
match = ^ ".github/"

[UploadToZef]

[Badges]
provider = github-actions/linux.yml
provider = github-actions/macos.yml
provider = github-actions/windows.yml

; execute some commands after `mi6 build`
[RunAfterBuild]
; cmd = some shell command here
cmd = raku --doc=Markdown docs/USAGE.rakudoc > ./USAGE.md
